// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dapimmudwfhgojtfqhgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhcGltbXVkd2ZoZ29qdGZxaGdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5ODkzNzQsImV4cCI6MjA1ODU2NTM3NH0.SBbSc2kiD6NztWd7L4Adqy-oDEMn4v3I4o1t2ih-muI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);